config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, only:[:destroy, :index, :edit, :new, :create, :update]
  resources :users, only:[:destroy, :index, :show, :edit, :new, :create, :update]

  resources :users do
    resources :reports
    resources :subjects
  end

  resources :classrooms do
    resources :users, module: :classrooms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :user, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relación con reportes
  has_many :reports    
  has_many :subjects 
  belongs_to :classroom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = @classroom.users
  end

  def show
    
  end

  def edit
    
  end
  
  

  private

  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[update destroy edit]

  def index
    @posts = Post.order(created_at: :desc)
    @post = Post.new
  end

  def edit
  end


  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html {redirect_to posts_path, notice:"Noticia creada."}
      else
        format.html {redirect_to posts_path, alert:"No pudo ser creada la noticia."}
      end
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:titulo, :fecha, :contenido)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_user
  before_action :set_report, only: %i[update show destroy edit]
  def index
    @reports = Report.order(created_at: :desc) 
  end

  def show

  end

  def new
    @report = @user.reports.new
  end

  def create
    @report = @user.reports.new(report_params)
    respond_to do |format|
      if @report.save
        format.html {redirect_to user_reports_path, notice:"Reporte creado."}
      else
        format.html {redirect_to user_reports_path, alert:"No pudo ser creada el reporte."}
      end
    end
  end
  

  def edit
    
  end

  def update
    if @report.update(report_params)
      flash.notice = "Anotación actualizada"
      redirect_to  user_reports_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    flash.alert = "Anotación eliminada"
    redirect_to user_reports_path(@user)
  end
  
  private

  def set_user
    @user = User.find(params[:user_id])    
  end

  def set_report
    @report = @user.reports.find(params[:id])
  end
  
  def report_params
    params.require(:report).permit(:user_id, :titulo, :contenido, :fecha)
  end
  

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_user
  before_action :set_subject, only: %i[update show destroy edit]

  def index
    @subjects = @user.subjects.all
  end

  def show
    
  end
  

  def new
    @subject = @user.subjects.new
  end

  def create
    @subject = @user.subjects.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html {redirect_to user_subjects_path, notice:"subjecte creado."}
      else
        format.html {redirect_to user_subjects_path, alert:"No pudo ser creada el subjecte."}
      end
    end
  end
  
  def edit

  end

  def update
    if @user.subjects.update(subject_params)
      flash[:notice] = "Materia actualizad"
      redirect_to user_subjects_path 
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    flash.alert = "Materia eliminada"
    redirect_to user_subjects_path(@user)
  end
  
  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_subject
    @subject = @user.subjects.find(params[:id])  
  end
  
  def subject_params 
    params.require(:subject).permit(:user_id, :codigo, :nombre)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[update destroy edit show]
  # before_action :user_params

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  # def create
  #   @user = User.new(user_params)
  #   respond_to do |format|
  #     if @user.save
  #       format.html {redirect_to users_path, notice:"Usuario creado."}
  #     else
  #       format.html {redirect_to users_path, alert:"No pudo ser creado el usuario."}
  #     end
  #   end
  # end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to cursos_path
      flash.notice= "User creado"

    else
      render :new
    end
  end

  def edit
  end

  private 

  def set_user
    @user = User.find(params[:id])
  end

  # def user_params
  #   # params.require(:user).permit(:identificacion, :password, :password_confirmation, :primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :telefono, :sexo, :direccion, :fecha_nacimiento)
  #   params.require(:user).permit(:email, :password, :password_confirmation)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Notificaciones TOASTR
    def custom_bootstrap_flash
        flash_messages = []
        flash.each do |type, message|
            type = 'info' if type == 'notice'
            type = 'success' if type == 'success'
            type = 'error'   if type == 'alert'
            text = "<script>toastr.#{type}('#{message}');</script>"
            flash_messages << text.html_safe if message
        end
        flash_messages.join("\n").html_safe
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classrooms/edit.html.erb
<h1>Vista edit de curso</h1>

app/views/classrooms/index.html.erb
<h1>Classrooms#index</h1>
<p>Find me in app/views/classrooms/index.html.erb</p>

app/views/classrooms/show.html.erb
<h1>Vista show curso</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>NEOPA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= custom_bootstrap_flash %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card shadow rounded">
  <div class="card-body">
    <%= simple_form_for(@post) do |f| %>
      <%= f.input :titulo, class:"rounded"%>
      <%= f.input :contenido, class:"rounded"%>
      <%= f.input :fecha%>
      <%= f.submit "Publicar", class:"btn btn-primary shadow"%>
    <%end%>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="card rounded shadow mt-2">
  <div class="card-body">
    <h3 class="font-weight-bold"> <%= post.titulo%></h3>
    <p class=""><%= post.contenido%></p>
    <p class=""><%= post.fecha%></p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Noticias#edit</h1>
<p>Find me in app/views/noticias/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container-fluid mt-5 mb-5">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <%= render "form"%>

      <div class="row mt-5 d-block">
        <div class="col-md-12">
          <%= render @posts%>
        </div>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Noticias#new</h1>
<p>Find me in app/views/noticias/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Noticias#show</h1>
<p>Find me in app/views/noticias/show.html.erb</p>

app/views/reports/_edit.html.erb
<h2 class="text-center mt-5">Editar anotación</h2>
<%= render 'form' %>

app/views/reports/_form.html.erb
<div class="row">
  <div class="col-md-5 mx-auto">
    <div class="card shadow rounded">
      <div class="card-body">
        <div class="box">
          <%= simple_form_for [@user, @report] do |f| %>
            <%= f.input :titulo, class:"rounded"%>
            <%= f.hidden_field :contenido, id: "mcontenido" %>
            <%= f.label :contenido%>
            <trix-editor input="mcontenido"></trix-editor>
            <%= f.input :fecha%>
            <%= f.submit "Enviar", class:"btn btn-primary shadow"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/reports/_report.html.erb
<tr>
    <td><%= link_to report.titulo, user_report_path(@user, report) %></td>
    <td><%= sanitize report.contenido %></td>
    <td><%= report.fecha %></td>
    <td><%= link_to "Editar", edit_user_report_path(@user, report) %></td>
    <td><%= link_to "Eliminar", user_report_path(@user, report),method: :delete, data: {confirm: "¿Estas seguro de eliminar esta anotación.?"} %></td>
</tr>

app/views/reports/edit.html.erb
<h2 class="text-center mt-5">Editar anotación</h2>
<%= render 'form' %>

app/views/reports/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 mt-5 mx-auto">
            <div class="card rounded shadow-lg">
                <div class="card-body">
                    <div class="box">
                        <%= link_to  "Generar reporte", new_user_report_path(@user, @report), class: "btn btn-info btn-sm mb-2" %>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <th>Titulo:</th>
                                    <th>Contenido:</th>
                                    <th>Fecha:</th>
                                    <th>Editar:</th>
                                    <th>Eliminar:</th>
                                </thead>
                                <tbody>
                                    <%= render @reports %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reports/new.html.erb
<h3 class="text-center mt-5">Generar anotación</h3>
<%= render 'form', report: @report, user: @user %>

app/views/reports/show.html.erb
<h3 class="text-center mt-5">Datos de la anotación</h3>

<div class="row">
    <div class="col-md-4 mx-auto">
        <div class="card shadow-lg">
            <div class="card-body">
                <div class="box">
                    <h4><strong>Fecha: </strong> <%= @report.fecha %> </h4>
                    <p><strong>Título: </strong> <%= @report.titulo %> </p>
                    <p><strong>Contenido: </strong> <%= sanitize @report.contenido %> </p>
                    <%= link_to "Editar", edit_user_report_path(@user, @report), class: "btn btn-warning btn-block" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/subjects/_form.html.erb
<div class="row">
    <div class="col-md-4 mx-auto">
        <div class="card shadow rounded">
            <div class="card-body">
              <%= simple_form_for [@user, @subject ] do |f| %>
                <%= f.input :codigo, class:"rounded"%>
                <%= f.input :nombre, class:"rounded"%>
                <%= f.submit "Enviar", class:"btn btn-primary shadow"%>
              <%end%>
            </div>
          </div>
    </div>
</div>

app/views/subjects/_subject.html.erb
<tr>
    <td><%= subject.codigo %></td>
    <td><%= subject.nombre %></td>
    <td><%= link_to "Editar", edit_user_subject_path(@user, subject) %></td>
    <td><%= link_to "Eliminar", user_subject_path(@user, subject), method: :delete, data:{ confirm: "¿Estas seguro de eliminar esta materia?" } %></td>
</tr>

app/views/subjects/edit.html.erb
<h3 class="text-center mt-5">Actualizar matería</h3>
<%= render 'form' %>

app/views/subjects/index.html.erb
<h3 class="text-center mt-5">Lista de materias</h3>
<div class="row">
    <div class="col-md-10 mt-5 mx-auto">
        <div class="card shadow-lg">
            <div class="card-body">
                <div class="box">
                    <%= link_to "Generar materia", new_user_subject_path(@user, @subject), class: "mb-2 btn btn-info btn-sm" %>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <th>Codígo</th>
                                <th>Nombre</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </thead>
                            <tbody>
                                <%= render @subjects %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/subjects/new.html.erb
<h3 class="text-center mt-5">Crear matería</h3>
<%= render 'form' %>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-5 mt-5 mx-auto">
      <div class="card">
        <div class="card-body">
          <div class="box">
            <%= simple_form_for(@user) do |f| %> 
            <%= f.input :email %>

            <div class="row">
              <div class="col"><%= f.input :password %></div>
              <div class="col"><%= f.input :password_confirmation %></div>
            </div>
  
            <div class="row">
              <div class="col">
                <div class="d-flex justify-content-center">
                  <%= f.button :submit, class: "btn-primary btn-block" %>
                </div>
              </div>
  
              <div class="col">
                <div class="d-flex justify-content-center">
                  <%= link_to 'Regresar' , users_path, class: "btn
                  btn-warning btn-block" %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/_user.html.erb
<tr>
    <td><%= user.email %></td>
    <td><%= link_to "ver", user_path(user) %></td>
</tr>

app/views/users/index.html.erb
<h2 class="text-center mt-5">Lista de usuarios</h2>

<div class="row">
    <div class="col-md-10 mx-auto">
        <div class="card shadow-lg">
            <div class="card-body">
                <div class="box">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <th>Email</th>
                                <th>Ver</th>
                            </thead>
                            <tbody>
                                <%= render @users %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h3 class="text-center mt-5">Crear usuario</h3>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-5 mt-5 mx-auto">
        <div class="card shadow-lg">
            <div class="card-body">
                <div class="box">
                    <h3 class="text-center">Datos del usuario</h3>
                    <h5><strong>Email: </strong><b> </b><%= @user.email %></h5>

                    <div class="row">
                        <div class="col"><%= link_to "Regresar", users_path(@user), class: "btn btn-success btn-sm btn-block" %></div>
                        <div class="col"><%= link_to "Editar", edit_user_path(@user), class: "btn btn-info btn-sm btn-block" %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>